# Generated by Django 4.1.6 on 2023-02-08 09:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργηθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ανανεωθηκε')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.CharField(max_length=120, unique=True)),
                ('sku_num', models.CharField(blank=True, editable=False, max_length=2, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργηθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ανανεωθηκε')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('VAT_agency', models.CharField(max_length=120)),
                ('VAT_num', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Greek VAT number. It must contain 9 digits.', regex='^[0-9]{9}$')], verbose_name='VAT number')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργηθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ανανεωθηκε')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('quote', models.CharField(max_length=220)),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text')], default='text', max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργηθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ανανεωθηκε')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered as 10 digits.No other punctuation required.', regex='^\\d{10}$')], verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Wrong email Format.', regex='([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\\.[A-Z|a-z]{2,})+')], verbose_name='Email')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργηθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ανανεωθηκε')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('area', models.CharField(max_length=200, verbose_name='Area')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('zipcode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Zipcode must be 5 digits.', regex='^\\d{5}$')], verbose_name='Postal code')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
