# Generated by Django 4.1.6 on 2023-02-10 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_address_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.CharField(blank=True, max_length=200, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Zipcode must be 5 digits.', regex='^\\d{5}$')], verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='person',
            field=models.CharField(blank=True, max_length=120, verbose_name='Eκπροσωπος'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered as 10 digits.No other punctuation required.', regex='^\\d{10}$')], verbose_name='Τηλεφωνο'),
        ),
    ]
